### ISSUE TITLE
Will Candid be replaced/augmented by wasm interface types eventually?

### ISSUE THREAD

**Issue by lachlansneff** [dfinity/candid#123]
[Wasm interface types](https://github.com/WebAssembly/interface-types/blob/linking-rebase/proposals/interface-types/Explainer.md) are a way for wasm modules to have a type-rich interface without any inherent serialization overhead. They're mostly intended to support low-cost calls between multiple wasm modules, but I suspect that they could be used for dfinity as well. They also don't require the module to include any serialization/deserialization code internally, all that gets generated at instantiation-time at the boundary automatically.

Interface types aren't ready for prime time, but if my understanding of candid is correct, there appears to be a lot of overlap.

Plus, languages like Rust will eventually support generating exported functions with interface types automatically without additional tooling.

**Comment by rossberg** [comment]
Interface types are for describing internal linking, Candid is for external messaging -- quite different contexts. Accordingly, what they provide operationally -- the serialisation format for Candid and the coercion combinators for interface types, are completely different mechanisms and one can't replace the other.

There is overlap in their basic types -- which is mostly a consequence of both starting from a canonical type algebra, and people talking to each other regularly ;). But there are also a number of differences. One reason we have our own IDL is that the IC has specific things that have to be expressible in interfaces: canisters, query/oneway functions, canister & function references, etc and more to come, such as cycles and funds. Interface types can't express any of that, but in turn define a whole set of mechanisms that make no sense for our use case.

Once interface types get somewhere we'll have to see if we could somehow make a connection and reap the similarities. But at this point that isn't obvious.
