### ISSUE TITLE
Duplicate spec in repo

### ISSUE THREAD

**Issue by rossberg** [dfinity/candid#145]
The Candid repo currently contains two versions of the spec, one in .adoc the other in .md format. And the former seems out of sync with the latter.

We should either generate one from the other, or get rid of one of the copies.

**Comment by chenyan-dfinity** [comment]
Related to https://github.com/dfinity/candid/issues/144, I think we should have a user-facing doc for Candid in .adoc to render in the SDK website, and keep the .md spec in the repo.
