### ISSUE TITLE
User’s guide: Information for rust developers

### ISSUE THREAD

**Issue by nomeata** [dfinity/candid#164]
The new user’s guide, added in #158, does not fully address the Rust-specific workflow and type mappings.

## Story

As a rust canister developer, I want Rust-specific Candid documentation, so that I can build Rust canisters that use Candid.

## Demo

* Go to https://github.com/dfinity/candid/blob/master/docs/modules/candid-guide/index.adoc
* Section “How do I use Candid as Rust canister developer?” has useful information
* In the reference section, all types describe their mapping to rust types.

**Comment by lsgunnlsgunn** [comment]
2 points for updating this section:
https://github.com/dfinity/candid/blob/master/docs/modules/candid-guide/pages/candid-types.adoc
Corresponding Rust type
