### ISSUE TITLE
User’s guide: Information for JS developers

### ISSUE THREAD

**Issue by nomeata** [dfinity/candid#165]
The new user’s guide, added in #158, does not fully address the JS-specific workflow and type mappings.

## Story

As a JS frontend developer, I want JS-specific Candid documentation, so that I can build JS frontends that use Candid well.

## Demo

* Go to https://github.com/dfinity/candid/blob/master/docs/modules/candid-guide/index.adoc
* Section “How do I use Candid as JavaScript front-end developer?” has useful information
* In the reference section, all types describe their mapping to JS values

**Comment by lsgunnlsgunn** [comment]
The 2pts is for updating
https://github.com/dfinity/candid/blob/master/docs/modules/candid-guide/pages/candid-types.adoc
corresponding JS type sections.
