### ISSUE TITLE
[Bug] candid/tests/parse_type.rs is incompatible with the grammar

### ISSUE THREAD

**Issue by seniorjoinu** [dfinity/candid#20]
I'm building a custom IDL parser using this repository's spec and tests, but it seems like there is an error.

**parse_type.rs**
```
type broker = service {
  find : (name: text) ->
    (service {up:() -> (); current:() -> (nat32)}); <<< missing semicolon here, but compiles
};
```
**IDL.md**
```
<actortype> ::= { <methtype>;* } <<< semicolon is not optional
```

**Comment by chenyan-dfinity** [comment]
As a convention for most parser specifications, the separator inside `*` is optional for the last item. 

Same is true for function type `<functype>  ::= ( <argtype>,* ) -> ( <argtype>,* ) <funcann>*`. You can write `(nat,) -> (nat,)` but most people will just write `(nat) -> (nat)`.
