### ISSUE TITLE
Disable/warn opt rule for textual parser

### ISSUE THREAD

**Issue by chenyan-dfinity** [dfinity/candid#214]
when `dfx call` takes an `opt` type, the opt subtyping rule essentially turns off the type checking. We need to disable or at least warn about the use of opt subtyping rules in the parser.

**Comment by nomeata** [comment]
I wonder how useful it is in general to apply subtyping here.  Subtyping is meant to be used when A sends a message to B according to an old `B.did`, so really only should play a role during decoding a message from another party.

When A is a CLI interface that parses a textual argument according to A’s believe of B’s interface, we don’t need to apply full subtyping, we merely need to use `B.did` to help resolve overloading, and maybe for convenience stuff (e.g. _omitting_ optional arguments).

I don’t see a point in ignoring additional record fields, doing the full `opt`-field handling etc.
