### ISSUE TITLE
The Choose File option doesn't seem to work

### ISSUE THREAD

**Issue by lsgunnlsgunn** [dfinity/candid#228]
I copied the `hello.did` file to the project root directory (because I can't browse to the hidden `.dfx/local/canisters` directory).
I navigated to the UI canister iD http://localhost:8000/?canisterId=r7inp-6aaaa-aaaaa-aaabq-cai
I clicked Choose file and select my hello.did file.
![image](https://user-images.githubusercontent.com/44206363/118194025-8b4b5580-b3fd-11eb-896d-cd3f1f4748e5.png)
I clicked Go.
I get No file chosen:
![image](https://user-images.githubusercontent.com/44206363/118194081-a3bb7000-b3fd-11eb-9859-ff459a5d7c28.png)
 This is a cool feature for when people want to share their did files, but it didn't work for me.

**Comment by chenyan-dfinity** [comment]
This is expected. You need to provide the canister ID for the `hello` canister.

**Comment by lsgunnlsgunn** [comment]
So to clarify you need to provide both the canister identifier and the did file ?

**Comment by chenyan-dfinity** [comment]
Canister id is required. The did file is optional as described on the page.
