### ISSUE TITLE
Invalid data: Invalid IDL blob

### ISSUE THREAD

**Issue by DelandPro** [dfinity/candid#265]
Not support by candid;

Invalid data: Invalid IDL blob ,when a method return CustomResult .
```Rust
pub enum CustomResult {
    Ok(Option<Error>),
    Err(Error),
}
```

**Comment by chenyan-dfinity** [comment]
Can you provide more context? Where does the error come from? Do you `#derive(CandidType, Deserialize)` for `CustomResult`?

**Comment by DelandPro** [comment]
https://github.com/Deland-Labs/dfinity-fungible-token-standard/blob/f291aa811c53500cacbe0990f061e410e4cafc90/Makefile#L34

this line return Invalid data: Invalid IDL blob.

But our team test it at https://github.com/witterlee/pub_sub_dfinity/blob/d30317ffb3403a238909e13d08a9c55e92ecf4f0/src/publish/src/lib.rs#L65.
return a valid IDL result.
I do not know why?
