### ISSUE TITLE
help request: candid::export_service!()

### ISSUE THREAD

**Issue by BrantBrown** [dfinity/candid#282]
Our developer create a function-like macro and use `candid::export_service!();` inside

https://github.com/Deland-Labs/dfinity-fungible-token-standard/blob/aaa0dcd7c8eee772778693359a60421c19339725/rust/dft_derive/src/func.rs#L662

But when use it like blow:
https://github.com/Deland-Labs/dfinity-fungible-token-standard/blob/aaa0dcd7c8eee772778693359a60421c19339725/rust/dft_basic/src/lib.rs#L7

When we try to call `dfx canister call dft_basic __get_candid_interface_tmp_hack` ,it  returns `("service : {}")`

We try use candid source code, and find `candid::export_service!()` executed before` candid_method macro`
 >  insert code ` println!("candid_method name is {}",name);` to [here](https://github.com/dfinity/candid/blob/061c8b76baf165dbce8cd7fda4efc141b9645846/rust/candid_derive/src/func.rs#L36) 

 >  insert code ` println!("export_service called");` to [here](https://github.com/dfinity/candid/blob/061c8b76baf165dbce8cd7fda4efc141b9645846/rust/candid_derive/src/func.rs#L84) 

> we get console log like
 ```
export_service called
candid_method name is __get_candid_interface_tmp_hack
candid_method name is transactionById
candid_method name is lastTransactions
candid_method name is transactionByIndex
candid_method name is tokenInfo
candid_method name is setFeeTo
candid_method name is setFee
candid_method name is transfer
candid_method name is transferFrom
candid_method name is allowancesOf
candid_method name is approve
candid_method name is allowance
candid_method name is balanceOf
candid_method name is setLogo
candid_method name is logo
candid_method name is setExtend
candid_method name is extend
candid_method name is meta
candid_method name is fee
candid_method name is totalSupply
candid_method name is decimals
candid_method name is symbol
candid_method name is name
candid_method name is setOwner
candid_method name is owner

```

So if `candid::export_service!()` executed after ` candid_method macro` , [the code](https://github.com/Deland-Labs/dfinity-fungible-token-standard/blob/aaa0dcd7c8eee772778693359a60421c19339725/rust/dft_basic/src/lib.rs#L7) will works. what can we do it correct?

**Comment by chenyan-dfinity** [comment]
`candid::export_service!()` has to be the LAST code in your program. Try putting candid::export_service!() in at the end of `lib.rs`

**Comment by BrantBrown** [comment]
Thanks  @chenyan-dfinity
This issue can be closed.
