### ISSUE TITLE
[IDL-101] Serialization hints

### ISSUE THREAD

**Issue by seniorjoinu** [dfinity/candid#33]
Can you please help me to understand a couple of things?

`candid/IDL.md` section Serialisation -> Types says:
> We assume that the fields in a record or function type are sorted by increasing id and the methods in a service are sorted by name.

What is "sorted by increasing id" in these terms? Sorted in an order they appear in source `.did` file? 

How exactly does the type definition table works (one which assigns uint to a type)?
Is this correct that expressions of kind `type Example = opt record { nat; nat; }` (in other words - type definition expressions) are added to the type definition table? And every other appearance of type "Example" (when used as datatype id) should be serialized as the index of "Example" in the type definition table?
Is this correct that the type in expression like 
```
service A {
  foo : (vec opt text) -> () oneway;
             ^------^ this complete type
}
```
is also added to the type definition table if it didn't appear earlier? Even if there was no expression like `type OptText = opt text;` met before.

After parse of a `.did` file one can end up having a "complete" type definition table - which contains every type that appear in a file. Should she use this type definition table when serializing a method call or she should somehow filter this table so it would contain only types that are really needed for the serialization of this method call? Is the order of types in the type definition table matters? How do one assert the correct order?

**Comment by alexabsmith** [comment]
Thanks for your thoughts here @seniorjoinu. This looks more like something we would love to have discussed in our forum vs. here on the repo. If you can please copy-paste there, that would be great. We will also update our contributing guidelines to clarify how we anticipate issues and PRs to be used. Thank you again!
