### ISSUE TITLE
Underscore should be accepted inside an hexnum

### ISSUE THREAD

**Issue by Alaanor** [dfinity/candid#339]
Hello,

While reading the candid spec I noticed a small difference between the implementation and the spec. While I don't personally need it, I figured out it would be sad to not point out.

```
> cat correct.did
type foo = record {
   "\u{1000}": foo;
};
> didc check correct.did
> cat wrong.did
type foo = record {
    "\u{10_00}": foo;
};
> didc check wrong.did
error: parser error
  ┌─ wrong.did:2:6
  │
2 │     "\u{10_00}": foo;
  │      ^^^^^ Unexpected string \u{10

Error: Candid parser error: Unexpected string \u{10 at 25..30

Caused by:
    Unexpected string \u{10 at 25..30
```

Here are some extracted rules from the [spec](https://github.com/dfinity/candid/blob/e7abc462fd54e72e3449999169c12e9f5209d091/spec/Candid.md):
```
<text>   ::= " <char>* "
<char>   ::= ... | \u{ <hexnum> }
<hexnum> ::= <hex>(_? <hex>)*
<hex>    ::= <digit> | A..F | a..f
```

According to those rule I was expecting `\u{ffff}`, `\u{f_f_f_f}`, `\u{ff_ff}`, ... to be all correct.

I hope I did read the grammar correctly and the issue make sense. Also side note, the title make it sound like the implementation is the one wrong, but I'm trying to point out at the difference rather.

**Comment by nomeata** [comment]
Thanks for spotting that! We should add that to the (implementation-independent) test suite.
