### ISSUE TITLE
Should deriving `CandidType` work in this scenario?

### ISSUE THREAD

**Issue by paulyoung** [dfinity/candid#356]
Below is a minimal example of my attempt to derive `CandidType` on a struct where a field contains a value whose type originates in an external crate.

I assumed this would work but I get an error which says `the trait bound Foo: CandidType is not satisfied`. Is this expected?

```rust
#[derive(CandidType, Deserialize)]
pub struct MyStruct {
    pub foos: BTreeSet<external_crate::Foo>,
}

```

The enum is defined as follows in the external crate. I've enabled the `serde1` feature in my `Cargo.toml` file.

```rust
const SIZE_OF_BAR: usize = 20;
```

```rust
#[derive(PartialEq, Eq, Hash, Ord, PartialOrd, Clone, Copy)]
#[cfg_attr(feature = "serde1", derive(serde::Serialize, serde::Deserialize))]
pub enum Foo {
    Bar([u8; SIZE_OF_BAR]),
}
```

Is the issue that `CandidType` can't be derived because of the `enum`?

**Comment by paulyoung** [comment]
I haven't tested this yet but I think this is how I would implement the necessary traits by hand if necessary.

Any advice is appreciated.

```rust
use derive_more::{Deref, Display};
use ic_cdk::export::candid::types::{Compound, Field, Label, Serializer, Type};
use ic_cdk::export::candid::{CandidType, Deserialize};

// Newtype so we can implement Candid and Deserialize traits
#[derive(Clone, Debug, Deref, Deserialize, Display, Eq, Ord, PartialEq, PartialOrd)]
pub struct Foo(pub external_crate::Foo);

impl CandidType for Foo {
    fn _ty() -> Type {
        Type::Record(vec![Field {
            id: Label::Id(0),
            ty: Type::Variant(vec![Field {
                id: Label::Named("Bar".to_owned()),
                ty: Type::Vec(Box::new(Type::Nat8)),
            }]),
        }])
    }
    fn idl_serialize<S>(&self, serializer: S) -> Result<(), S::Error>
    where
        S: Serializer,
    {
        let mut ser = serializer.serialize_struct()?;

        let element = match self.0 {
            external_crate::Foo::Bar(ref v) => {
                let mut ser = serializer.serialize_variant(0)?;
                Compound::serialize_element(&mut ser, v)
            }
        }?;

        Compound::serialize_element(&mut ser, &element)?;

        Ok(())
    }
}
```

**Comment by chenyan-dfinity** [comment]
Yes, the above code looks good to me. Since you cannot derive CandidType for external crates, you will have to wrap it in a newtype and derive CandidType manually.

**Comment by paulyoung** [comment]
There's an error with the above because `serializer` is used again after it's moved (`serializer.serialize_struct`). I'm struggling to understand how to address this.

Is this a known limitation, or is there some trick to using `serializer` more than once?

**Comment by chenyan-dfinity** [comment]
For the newtype `_ty()` can just return `Type::Variant` instead of a 1-tuple of variant. 

`idl_serializer` assumes the implementation is recursive descent, which means `serializer` is linear. It should be fine if the type is a variant without the wrapper.

**Comment by paulyoung** [comment]
Thanks for the help!
