### ISSUE TITLE
 IDL error: variant or record tag out of order"

### ISSUE THREAD

**Issue by marspoolxyz** [dfinity/candid#387]
Hello there
When i tried to upgrade the canister with a code change getting the below error.

Caused by: Failed to install wasm module to canister 'prod_finance'.
Failed to install wasm in canister '6s6yi-xxxxx-xxxx-qc6iq-cai'.
Failed to install wasm.
The Replica returned an error: code 5, message: "Canister 6s6yi-xxxx-xxxx-qc6iq-cai trapped explicitly: IDL error: variant or record tag out of order"

Any advice

**Comment by nomeata** [comment]
Looks like https://forum.dfinity.org/t/invocation-error/10036 and https://forum.dfinity.org/t/upgrade-is-not-working-on-canister/15793.

Are you using a motoko canister? (The error message looks like it). What is the type of your `actor class` argument? And what are the options you pass to `dfx` when upgrading?

**Comment by marspoolxyz** [comment]
actor class prod_finance (_owner: Principal) {
}

MODE="upgrade"
OWNER="principal \"$( \
    dfx identity get-principal
)\""
dfx canister --network ic install prod_finance --argument="'($OWNER)'" --mode $MODE

**Comment by chenyan-dfinity** [comment]
Can you show the code diff before and after the upgrade?
