### ISSUE TITLE
As a developer using a custom build, when going to the Candid UI link generated by dfx deploy, I want to be able to choose a did file when the Candid canister cannot fetch the candid file

### ISSUE THREAD

**Issue by ArjaanBuijk** [dfinity/candid#391]
I'm always frustrated when I use a custom build (C++ in my case) and the `dfx deploy` command provides me a link to the Candid UI but because the did file is not available, the Candid UI throws an error.

In detail, it looks like this:

```bash
dfx deploy
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "default" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying all canisters.
Creating canisters...
Creating canister canister_1...
canister_1 canister created with canister id: rrkah-fqaaa-aaaaa-aaaaq-cai
Building canisters...
Executing ...my custom stuff...
...
Shrink WASM module size.
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "ryjl3-tyaaa-aaaaa-aaaba-cai"
Installing code for canister canister_1, with canister ID rrkah-fqaaa-aaaaa-aaaaq-cai
Deployed canisters.
URLs:
  Backend canister via Candid interface:
    canister_1: http://127.0.0.1:8000/?canisterId=ryjl3-tyaaa-aaaaa-aaaba-cai&id=rrkah-fqaaa-aaaaa-aaaaq-cai
```

When I go to the Candid interface in the browser using the provided link `http://127.0.0.1:8000/?canisterId=ryjl3-tyaaa-aaaaa-aaaba-cai&id=rrkah-fqaaa-aaaaa-aaaaq-cai`, it gives this error:

```bash
An error happened in Candid canister:
Error: Cannot fetch candid file
    at Object.fetchActor (http://127.0.0.1:8000/index.js:2:265325)
    at async http://127.0.0.1:8000/index.js:2:275457
```

**Describe the solution you'd like**
I can use the Candid UI just fine, if I first go the Candid UI main page, in above example that would be http://127.0.0.1:8000/?canisterId=ryjl3-tyaaa-aaaaa-aaaba-cai, and I then I am able to:
- provide a canister ID, in above example `rrkah-fqaaa-aaaaa-aaaaq-cai`
- choose a did file, by selecting it from disk

It would be nice if the Candid UI did not throw an error message when the did file cannot be fetched, but instead, pops up a warning, and goes to the Candid UI main page, with the canister ID already prefilled. I then simply select the did file from disk and we're good to go.

**Comment by chenyan-dfinity** [comment]
You can now use ic-wasm to embed the did file into the wasm module: `ic-wasm a.wasm -o a.wasm metadata candid:service -v public -f a.did`
