### ISSUE TITLE
As a developer, I want a new `candid::types::Null` type so that I can differentiate between `null` and `()` (or nothingness)

### ISSUE THREAD

**Issue by dansteren** [dfinity/candid#411]
**Is your feature request related to a problem? Please describe.**
If I have a canister method in rust that returns nothing, I say the return type is `()`. If I want to instead say that it returns null I put the return type as `(())`. However, both are equivalent in Rust. In fact, when using the latter (with double parens), Rust tells me that there is an unnecessary set of parenthesis.

To give a concrete example of why this is a problem: if I want to implement a trait that converts a value into a candid null (i.e. `(())`) I cannot do so because `()` and `(())` are the same type. For example, consider the following trait and implementation:

```rust
impl CdkActTryFromVmValue<()> for boa_engine::JsValue {
    fn try_from_vm_value(self) -> Result<(), String> {
        if self.is_undefined() == true { Ok(()) }
        else { Err("JsValue is not undefined".to_string()) }
    }
}
```
This will convert `boa_engine::JsValue`s that are `undefined` into Rust's unit type: `()`. If I want to create an additional trait to handle JS values that are `.is_null()`, I cannot do so, because making an impl for `(())` is equivalent to making an impl for `()` so the two will clash. So the best I can do is have an impl that detects if `self.is_null() || self.is_undefined()`, and convert either to `()`, but this isn't really the same nor what I want.

**Describe the solution you'd like**
Instead of using `(())` to represent candid's `null` type, I would prefer that we make an explicit new rust struct/enum such as `candid::types::Null`. This would match the `candid::types::reserved::Reserved` and `candid::types::reserved::Empty` types that already exist but don't have good Rust counterparts.

**Describe alternatives you've considered**
This isn't necessarily a blocker. There are ways to get around this using the `(())` type, but it's just less than ideal.

**Additional context**
- https://github.com/dfinity/agent-js/issues/581

**Comment by chenyan-dfinity** [comment]
You can use `((),)` instead

**Comment by dansteren** [comment]
I ran into another scenario where having this other type would be useful. In [Azle](https://github.com/demergent-labs/azle) we parse JS code and create Rust types for all the declared TS types. When we have something like `type VoidAlias = Alias<void>` we need to create a rust equivalent type to represent this. So we generate the rust code: `type VoidAlias = ();`. We currently wrap all of our canister method return types in parens. So when we have a canister method that returns a VoidAlias it generates a rust return signatures of `-> (VoidAlias)` which becomes `(())`.

I'm sure there's things that we could do differently to get around this, but again, it seems like things would be much easier for us if there was a `candid::types::Null` type that we could use instead.

I even considered making some sort of type like this without our own project and just aliasing it to `()` but I think we'd run into the same issue as above.

**Comment by chenyan-dfinity** [comment]
I think it's always safe to add a comma in the return type signature, e.g, `-> (VoidAlias,)`, `-> (VoidAlias, (), VoidAlias,)`
