### ISSUE TITLE
export service in rust will overwrite the types with the same fields 

### ISSUE THREAD

**Issue by gabrielnic** [dfinity/candid#412]
Consider the following code: 
```rust 
#[derive(CandidType,` Clone, Serialize, Deserialize)]
pub struct User1 {
  id: String,
  name: String,
  age: u8,
}

#[derive(CandidType, Clone, Serialize, Deserialize)]
pub struct User2 {
  id: String,
  name: String,
  age: u8,
}


#[query]
#[candid_method(query)]
pub fn test1(e: User1) {
}

#[query]
#[candid_method(query)]
pub fn test2(e: User2) {
}

#[test]
pub fn generate_candid() -> () {
  use std::env;
  use std::fs::write;
  use std::path::PathBuf;

  candid::export_service!();
 
  let dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
  let dir = dir.parent().unwrap().join("candid");
  write(dir.join(format!("test.did")), __export_service()).expect("Write failed.");
}
```

I would expect the candid file to be 

```
type User1 = record { id : text; age : nat8; name : text };
type User2 = record { id : text; age : nat8; name : text };
  test1 : (User1) -> () query;
  test2 : (User2) -> () query;
```

but the actual output is this

```
type User1 = record { id : text; age : nat8; name : text };
  test1 : (User1) -> () query;
  test2 : (User1) -> () query;
```
It seems that candid copy the struct reference and check if the same structure exists and if it does it's omitted.

**Comment by chenyan-dfinity** [comment]
This is a known behavior: https://github.com/dfinity/candid/blob/master/rust/candid/src/types/internal.rs#L83. But technically not a bug. Because Candid follows structure typing, `User1` and `User2` are exactly the same, it's not wrong to use `User1` when the underlying Rust code uses `User2`. But I understand this is confusing for documentation purposes. 

One workaround can be to let users provide their own did file and the build process will check if the provided did file is a subtype of the generated one.

**Comment by borovan** [comment]
Hey, sorry about the confusion.  We had some crossed wires internally about what was going on.

Yes, that is the default behaviour for Candid and that's understood.  What we meant to point out was there seems to be irregularity in the derive macro code for the Rust implementation of Candid.

We had ten identical structs, so we expected to either get 10 entries in Candid (if it wasn't structurally typed), or 1 (if it was - and that's cleared up now.

We got 2... or at least I did, the rest of the team can't really replicate it yet.  I have on two separate computers though.  I managed to reduce it down to the following code....

```
#[derive(CandidType, Deserialize)]
pub struct Cat1 {
    pub id: String,
}

#[update]
#[candid_method(update)]
async fn create_a_cat(e: Cat1) -> api::CreateResult {
    Ok("".into())
}

#[derive(CandidType, Deserialize)]
pub struct Cat {
    pub id: String,
}

#[update]
#[candid_method(update)]
async fn create_b_cat(e: Cat) -> api::CreateResult {
    Ok("".into())
}
```

```
type Cat = record { id : text };
type Cat1 = record { id : text };
service : () -> {
  create_a_cat : (Cat1) -> (Result);
  create_b_cat : (Cat) -> (Result);
}
```

It seems that if the first type has a longer name than the second type it creates two.  If I change the Cat to Cat2 then it works as intended with only one candid type created.

**Comment by chenyan-dfinity** [comment]
Correct. The algorithm is trying to find the shortest name at the time of the lookup. Depending on the order the compiler processes these type definitions, it may get different result. That's also why you may not be able to reliably replicate it. Again, it's still correct, but not nice.

**Comment by borovan** [comment]
oh thanks, this explains it.  We have a workaround where our auto-generated classes make more sense... just thought it may be a bug.

**Comment by gabrielnic** [comment]
hey @chenyan-dfinity I get that's how candid works, could you have a look and maybe comment here please: https://forum.dfinity.org/t/deduplication-of-candid-types-in-rust/19079 thanks, will close this for now.
