### ISSUE TITLE
export_service macro should honor method name in `#[ic_cdk_macros::query(name = "method_name")]`

### ISSUE THREAD

**Issue by dansteren** [dfinity/candid#418]
**Describe the bug**
If a rust method is exposed to the IC under a different name using the `name` attribute in `#[ic_cdk_macros::query(name = "method_name")]`, the `export_service` macro should also honor that name when generating the corresponding candid.

**To Reproduce**
1. Annotate a canister method with `#[candid::candid_method(query)]` and `#[ic_cdk_macros::query(name = "candid_method")]`
2. Call the `export_service` macro
3. Notice that the generated candid exposes the native rust function name, not the name provided to `ic_cdk_marcros::query`.

OR

1. Clone https://github.com/dansteren/export_service_bug
2. Follow the steps to reproduce listed in the readme

**Expected behavior**
Calling the export_service macro should generate a candid file where the method matches the name passed to `ic_cdk_marcros::query`

**Comment by chenyan-dfinity** [comment]
Ack. We are in the process of merging these two attributes. Before that, `candid_method` has a `rename` attribute. If you make it the same as `query(name = "...")`, it should work.

**Comment by dansteren** [comment]
That worked, Thanks! Just added that rename attribute for now. E.g.

```rust
#[candid::candid_method(query, rename = "candid_method")]
#[ic_cdk_macros::query(name = "candid_method")]
pub fn rust_method() -> bool {
    true
}
```

If it's easy to add into [the documenation](https://docs.rs/candid/latest/candid/attr.candid_method.html) that would be helpful for others in the future. Otherwise I look forward to the two attributes merging in the future. That will be much better.

Thanks!
