### ISSUE TITLE
Candid deserializes to wrong Enum variant

### ISSUE THREAD

**Issue by ufoscout** [dfinity/candid#423]
Deserializing a vector of enums produces wrong values.
Here is a complete reproducer of the problem:

```rust
    #[test]
    fn test_enum_candid_encoding() {
        
        #[derive(Debug, CandidType, Deserialize, PartialEq, Eq)]
        pub enum Values {
            One,
            Two,
            Three,
        }

        let text_value = r#"
        (
            vec { variant { One }; variant { Two } }
        )
        "#;

        let args = IDLArgs::from_str(text_value).unwrap();
        let encoded: Vec<u8> = args.to_bytes().unwrap();

        let decoded = Decode!(encoded.as_slice(), Vec<Values>).unwrap();
        
        // This fails because decoded is vec![Values::One, Values::One]
        assert_eq!(vec![Values::One, Values::Two], decoded);
    }
```

**Comment by chenyan-dfinity** [comment]
Agreed. Parsing values without explicit types is only best effort, and not a recommended practice. In practice, you almost always know the candid types when parsing a value, and is strongly recommended to use `args.to_bytes_with_types()` instead of `to_bytes()`.

**Comment by ufoscout** [comment]
@chenyan-dfinity 
Could you please provide an example?
I copied and pasted this from the [documentation](https://docs.rs/candid/latest/candid/#operating-on-untyped-candid-values) but it still fails with my enum vector:

```rust
        let text_value = r#"
        (
            vec { variant { One }; variant { Two } }
        )
        "#;

        // Parse text format into IDLArgs for serialization
        let args: IDLArgs = text_value.parse().unwrap();
        let encoded: Vec<u8> = args.to_bytes().unwrap();

        // Deserialize into IDLArgs
        let decoded: IDLArgs = IDLArgs::from_bytes(&encoded).unwrap();
        assert_eq!(encoded, decoded.to_bytes().unwrap());

        // Convert IDLArgs to text format
        let output: String = decoded.to_string();
        let parsed_args: IDLArgs = output.parse().unwrap();
        let annotated_args = args.annotate_types(true, &TypeEnv::new(), &parsed_args.get_types()).unwrap();
```

This panics at the last line with error: `called Result::unwrap() on an Err value: Custom(variant field Two not found)`

**Comment by chenyan-dfinity** [comment]
I mean the encoding part needs to have types: https://github.com/dfinity/candid/blob/master/tools/didc/src/main.rs#L214.

On the other hand, unless you are developing a generic tool for Candid, you rarely need to parse a textual value and use `IDLArgs` directly. A more realistic example would be,
```
let bytes = Encode!(&[Values::One, Values::Two])?;
let vec = Decode!(&bytes, Vec<Values>)?;
```
