### ISSUE TITLE
[Bug] consistent view on newtype

### ISSUE THREAD

**Issue by chenyan-dfinity** [dfinity/candid#43]
```
enum E {
  A(i8),
}
```
When encoding `E`, Candid thinks field `A` is of type `record { 0: int8 }`, but decoding is expecting `i8` directly.

**Comment by hansl** [comment]
```
enum E {
  A(i8),
}
```

Isn't that `newtype_variant` and not `newtype_struct`?

**Comment by chenyan-dfinity** [comment]
`A(i8)` is a struct. `enum E(A)` is variant.
