### ISSUE TITLE
As a developer, I want `candid::Deserialize<'_>` to support `[u32; N]`

### ISSUE THREAD

**Issue by 0kenx** [dfinity/candid#448]
It's not immediately clear to me how to implement `candid::Deserialize<'_>` for `[u32; N]` (`TypeInner` gets in the way). Can someone implement this or point me in the right direction?

**Comment by chenyan-dfinity** [comment]
`candid::Deserialize` is simply an alias for `serde::Deserialize`. Maybe the fix should be made on the serde side?
