### ISSUE TITLE
Error deserializing Nat with serde and bincode.

### ISSUE THREAD

**Issue by levifeldman** [dfinity/candid#476]
Error: "Bincode does not support the serde::Deserializer::deserialize_any method". 

candid::Nat uses the deserialize_any method for its implementation of serde::Deserialize https://docs.rs/candid/latest/src/candid/types/number.rs.html#225.

The [bincode](https://docs.rs/bincode/1.3.3/bincode/index.html) binary serialization format is not compatible with the deserialize_any method.

Is there a way to support Nat deserialization without the deserialize_any method?

**Comment by chenyan-dfinity** [comment]
Because of subtyping check, it's not easy for Candid to avoid using `deserialize_any`. This issue is more of a request for `bincode` to support deserialize_any.

One workaround is to use `#[serde(deserialize_with)]` and provide your own deserializer.

**Comment by chenyan-dfinity** [comment]
Another workaround is to use `i128/u128` for `Int/Nat` type. The limitation is that it's only 128bit, and not infinite precision.
