### ISSUE TITLE
Display invalid field name in error message.

### ISSUE THREAD

**Issue by enzoh** [dfinity/candid#48]
When a user mistakenly uses and invalid record field name, the following error message is observed.
`Invalid data: Unable to convert IDL to bytes: field 2468089002 not found`
This appears to reference the hash of the invalid record field name and not the invalid record field name itself, which is somewhat ambiguous. Would awesome if we could display the unhashed value so that the user sees:
`Invalid data: Unable to convert IDL to bytes: field 'name' not found`

**Comment by seniorjoinu** [comment]
I don't know for sure, but it seems impossible (without spec change) to me.
Record values are serialized into pairs "field_name_hash"->"field_value". So no "field_name" is passed to a canister.
When a node parses this record value it can't tell what was the preimage of the "field_name_hash". It only knows some field names that are actually exist on a record.

I think this problem should be solved via strict typing.

**Comment by chenyan-dfinity** [comment]
It is possible if you consult with the candid file for the method signature. You can check which field name in the candid file matches the given hash.

**Comment by seniorjoinu** [comment]
But what if no field matches the given hash?

**Comment by chenyan-dfinity** [comment]
right, it's not possible for all cases. This issue is only about improving the parser for `dfx`. When users provide a non-existed field name to dfx, you can check with the candid file to report the error properly.
