### ISSUE TITLE
If there is an Unknown declaration in IDLProg, subsequent declarations cannot be obtained from TypeEnv.

### ISSUE THREAD

**Issue by linnefromice** [dfinity/candid#501]
Below is the last case of the test code.
Confirmed with candid 0.10, but reproduced with candid 0.9.

```rust
// candid = "0.10.0"
// candid_parser = "0.1.0"

#[cfg(test)]
mod tests {
    use std::ops::Deref;

    use candid::TypeEnv;
    use candid_parser::{IDLProg, check_prog};

    fn generate_type_env(ast: IDLProg) -> TypeEnv {
        let mut type_env = TypeEnv::new();
        let _ = check_prog(&mut type_env, &ast);
        type_env
    }

    #[test]
    fn test_only_primitive() {
        let did  = r#"
type RequestType = nat;
type ResponseType = text;"#.to_string();
        let ast: IDLProg = did.parse().unwrap();
        let type_env = generate_type_env(ast);
        assert_eq!(type_env.find_type("RequestType").unwrap().deref(), &candid::types::TypeInner::Nat);
        assert_eq!(type_env.find_type("ResponseType").unwrap().deref(), &candid::types::TypeInner::Text);
    }

    #[test]
    fn test_unknown_letter() {
        let did  = r#"
type RequestType = nat;
type ResponseType = UnknownType;"#.to_string();
        let ast: IDLProg = did.parse().unwrap();
        let type_env = generate_type_env(ast);
        assert_eq!(type_env.find_type("RequestType").unwrap().deref(), &candid::types::TypeInner::Nat);
        assert_eq!(type_env.find_type("ResponseType").unwrap().deref(), &candid::types::TypeInner::Unknown);
    }

    #[test]
    fn test_unknown_former() {
        let did  = r#"
type RequestType = UnknownType;
type ResponseType = text;"#.to_string();
        let ast: IDLProg = did.parse().unwrap();
        let type_env = generate_type_env(ast);
        assert_eq!(type_env.find_type("RequestType").unwrap().deref(), &candid::types::TypeInner::Unknown);
        assert_eq!(type_env.find_type("ResponseType").unwrap().deref(), &candid::types::TypeInner::Unknown); // NOTE: Why can't I get Text?
    }
}
```

**Comment by chenyan-dfinity** [comment]
Working as expected. `check_prog(&mut type_env, &ast)` return a result type, you need to `unwrap` the result in `generate_type_env`. 

`type RequestType = UnknownType;`, `UnknownType` doesn't exist, check_prog will error out.

**Comment by linnefromice** [comment]
@chenyan-dfinity Thanks for confirming.
My point is that if you find a definition that is determined to be Unknown first, then a Type using a primitive defined later is also Unknown.
Do you mean that this is the behavior as specified?
I would like you to compare `test_unknown_letter` and `test_unknown_former` test cases.

The types to be declared in did are the same, only the order of definition is different.
The only difference is the order of definition.
(I'm using candid crete in an app on icp and didn't notice this behavior and put a potential bug in it.)

**Comment by chenyan-dfinity** [comment]
The did file you provided is invalid, therefore, `TypeEnv` doesn't make any sense, and you shouldn't be looking at TypeEnv with invalid did file.

> if you find a definition that is determined to be Unknown first

This is never possible with a valid did file. No variable should be assigned to Unknown. We ensure this invariant via type checking.

**Comment by linnefromice** [comment]
I see. 
I'm still concerned about the difference in behavior when reading something invalid, though.

>We ensure this invariant via type checking.

Which API checks if .did or its string is correctly declared in input?

**Comment by linnefromice** [comment]
Thank you.
That's what you meant by your previous comment, sorry I didn't realize that.
