### ISSUE TITLE
Example of Candid tools within Github Actions

### ISSUE THREAD

**Issue by matthewhammer** [dfinity/candid#76]
Finished by https://github.com/matthewhammer/motoko-bigtest/pull/10

--------------
Originally:

I would like to show examples of using the Candid tools within Github Actions:
  - [x] download and install candid tools (e.g., [build from source](https://github.com/actions/checkout#checkout-multiple-repos-side-by-side), or get binary from Rust crates cache, or from a GH release?)
  - [x] test script captures a comprehensive log of all relevant canister behavior, as a candid value stored in a file (pipe output of `dfx canister call MyCanister getFullLog`)
  - [x] test script uses candiff to compare the latest log to an earlier one that is human readable, saved in the repo; any differences are also human readable (thanks to candiff)

**Comment by matthewhammer** [comment]
FYI: I also made [a similar issue specific to BigTest](https://github.com/matthewhammer/motoko-bigtest/pull/6), in that repo.

**Comment by chenyan-dfinity** [comment]
For the second item, this works:
```
didc decode `dfx canister call MyCanister getFullLog --output raw`
```

**Comment by matthewhammer** [comment]
PR for final item (and assembles all items all together):
   https://github.com/matthewhammer/motoko-bigtest/pull/8

**Comment by matthewhammer** [comment]
@chenyan-dfinity FYI there's some kind of mismatch between the parsing logic of `didc` and `candiff`
  https://github.com/matthewhammer/motoko-bigtest/runs/1021556118#step:10:159

I think it concerns whether they expect enclosing parens around an input / output value, or not.  (is it a unary tuple, or a value?)

**Comment by matthewhammer** [comment]
Any advice or ideas for the best resolution?

**Comment by chenyan-dfinity** [comment]
Yes, `candiff` is parsing a `IDLValue`, while `didc` is parsing `IDLArgs` (a vector of `IDLValue`). So pretty printing of IDLArgs always has a parenthesis. If you are comparing output from a method call (from dfx), it make more sense to work on `IDLArgs`, as method calls always return a sequence of values.

**Comment by matthewhammer** [comment]
Okay, I'll merge this as is, and fix the (superficial) mismatch in a subsequent PR to `candiff`.  Thanks.

**Comment by matthewhammer** [comment]
https://github.com/matthewhammer/motoko-bigtest/pull/10
